In [22]:
import pandas as pd
import numpy as np

In [23]:
df=pd.read_csv("trends.csv")
df

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26955 rows x 5 columns]

In [24]:
df.head()

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [25]:
df.tail()

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  object
 1   year      26955 non-null  int64
 2   category  26955 non-null  object
 3   rank      26955 non-null  int64
 4   query     26955 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.0+ MB

In [27]:
df.dtypes

location    object
year         int64
category    object
rank         int64
query       object
dtype: object

In [32]:
df.isnull().sum()

location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [33]:
df.nunique()

location       83
year           20
category     2450
rank            5
query       18431
dtype: int64

In [34]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
26950    False
26951    False
26952    False
26953    False
26954    False
Length: 26945, dtype: bool

In [35]:
df.drop_duplicates(inplace=True)

In [36]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
26950    False
26951    False
26952    False
26953    False
26954    False
Length: 26945, dtype: bool

In [37]:
df.describe()

               year         rank
count  26945.000000  26945.00000
mean    2015.241974      3.00000
std        3.564557      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000